mila_short_links_login:
    pattern:  /login
    defaults: { _controller: MilaShortLinksBundle:Auth:login }

mila_short_links_register:
    pattern:  /register
    defaults: { _controller: MilaShortLinksBundle:Auth:register }

mila_short_links_redirect:
    path:      /{code}
    defaults:  { _controller: MilaShortLinksBundle:Default:redirect }

mila_short_links_homepage:
    pattern:  /
    defaults: { _controller: MilaShortLinksBundle:Default:index }

